import streamlit as st
import pandas as pd


@st.cache_data(ttl=30)
def load_election_data():
    df = pd.DataFrame([
        {
            "constituency": "Kathmandu-1",
            "province": "Bagmati",
            "district": "Kathmandu",
            "candidate": "Candidate A",
            "party": "Party X",
            "votes": 24567,
            "runner_up": "Candidate B",
            "runner_up_party": "Party Y",
            "runner_up_votes": 21950,
            "status": "Leading",
            "count_pct": 82,
        },
        {
            "constituency": "Kathmandu-2",
            "province": "Bagmati",
            "district": "Kathmandu",
            "candidate": "Candidate C",
            "party": "Party Y",
            "votes": 30110,
            "runner_up": "Candidate D",
            "runner_up_party": "Party X",
            "runner_up_votes": 28775,
            "status": "Won",
            "count_pct": 100,
        },
        {
            "constituency": "Lalitpur-1",
            "province": "Bagmati",
            "district": "Lalitpur",
            "candidate": "Candidate E",
            "party": "Party Z",
            "votes": 18670,
            "runner_up": "Candidate F",
            "runner_up_party": "Party X",
            "runner_up_votes": 18011,
            "status": "Leading",
            "count_pct": 74,
        },
        {
            "constituency": "Kaski-1",
            "province": "Gandaki",
            "district": "Kaski",
            "candidate": "Candidate G",
            "party": "Party X",
            "votes": 27890,
            "runner_up": "Candidate H",
            "runner_up_party": "Party Z",
            "runner_up_votes": 25100,
            "status": "Won",
            "count_pct": 100,
        },
        {
            "constituency": "Morang-3",
            "province": "Koshi",
            "district": "Morang",
            "candidate": "Candidate I",
            "party": "Party Y",
            "votes": 19880,
            "runner_up": "Candidate J",
            "runner_up_party": "Party X",
            "runner_up_votes": 19320,
            "status": "Leading",
            "count_pct": 68,
        },
        {
            "constituency": "Rupandehi-2",
            "province": "Lumbini",
            "district": "Rupandehi",
            "candidate": "Candidate K",
            "party": "Party X",
            "votes": 22440,
            "runner_up": "Candidate L",
            "runner_up_party": "Party Y",
            "runner_up_votes": 22010,
            "status": "Leading",
            "count_pct": 77,
        },
        {
            "constituency": "Dhanusha-1",
            "province": "Madhesh",
            "district": "Dhanusha",
            "candidate": "Candidate M",
            "party": "Party Z",
            "votes": 26440,
            "runner_up": "Candidate N",
            "runner_up_party": "Party Y",
            "runner_up_votes": 24490,
            "status": "Won",
            "count_pct": 100,
        },
        {
            "constituency": "Banke-1",
            "province": "Lumbini",
            "district": "Banke",
            "candidate": "Candidate O",
            "party": "Party Y",
            "votes": 17420,
            "runner_up": "Candidate P",
            "runner_up_party": "Party Z",
            "runner_up_votes": 17100,
            "status": "Leading",
            "count_pct": 59,
        },
    ])

    df["margin"] = df["votes"] - df["runner_up_votes"]
    return df
